// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// AdunitsColumns holds the columns for the "adunits" table.
	AdunitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "unknow"},
	}
	// AdunitsTable holds the schema information for the "adunits" table.
	AdunitsTable = &schema.Table{
		Name:        "adunits",
		Columns:     AdunitsColumns,
		PrimaryKey:  []*schema.Column{AdunitsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdunitsTable,
	}
)

func init() {
}
