// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/songfei1983/go-api-server/ent/adunit"
)

// AdunitCreate is the builder for creating a Adunit entity.
type AdunitCreate struct {
	config
	mutation *AdunitMutation
	hooks    []Hook
}

// SetName sets the name field.
func (ac *AdunitCreate) SetName(s string) *AdunitCreate {
	ac.mutation.SetName(s)
	return ac
}

// SetNillableName sets the name field if the given value is not nil.
func (ac *AdunitCreate) SetNillableName(s *string) *AdunitCreate {
	if s != nil {
		ac.SetName(*s)
	}
	return ac
}

// Mutation returns the AdunitMutation object of the builder.
func (ac *AdunitCreate) Mutation() *AdunitMutation {
	return ac.mutation
}

// Save creates the Adunit in the database.
func (ac *AdunitCreate) Save(ctx context.Context) (*Adunit, error) {
	if _, ok := ac.mutation.Name(); !ok {
		v := adunit.DefaultName
		ac.mutation.SetName(v)
	}
	var (
		err  error
		node *Adunit
	)
	if len(ac.hooks) == 0 {
		node, err = ac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AdunitMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ac.mutation = mutation
			node, err = ac.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ac.hooks) - 1; i >= 0; i-- {
			mut = ac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AdunitCreate) SaveX(ctx context.Context) *Adunit {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ac *AdunitCreate) sqlSave(ctx context.Context) (*Adunit, error) {
	a, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	a.ID = int(id)
	return a, nil
}

func (ac *AdunitCreate) createSpec() (*Adunit, *sqlgraph.CreateSpec) {
	var (
		a     = &Adunit{config: ac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: adunit.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: adunit.FieldID,
			},
		}
	)
	if value, ok := ac.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: adunit.FieldName,
		})
		a.Name = value
	}
	return a, _spec
}
