// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/songfei1983/go-api-server/ent/adunit"
	"github.com/songfei1983/go-api-server/ent/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	adunitFields := schema.Adunit{}.Fields()
	_ = adunitFields
	// adunitDescName is the schema descriptor for name field.
	adunitDescName := adunitFields[0].Descriptor()
	// adunit.DefaultName holds the default value on creation for the name field.
	adunit.DefaultName = adunitDescName.Default.(string)
}
