log_leve: "debug"

database:
  driver: sqlite3
  dbname: test.db
#   driver: mysql
#   host: localhost
#   port: 3306
#   dbname: test
#   user: test
#   password: test

api_server:
  port: 8000
  host: localhost