// Code generated by entc, DO NOT EDIT.

package adunit

const (
	// Label holds the string label denoting the adunit type in the database.
	Label = "adunit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// Table holds the table name of the adunit in the database.
	Table = "adunits"
)

// Columns holds all SQL columns for adunit fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// DefaultName holds the default value on creation for the name field.
	DefaultName string
)
