basePath: /
definitions:
  errors.HTTPError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  model.KeyValue:
    properties:
      key:
        type: string
      value:
        type: object
    type: object
info:
  contact:
    name: fei song
  description: API REST in Golang with Echo Framework
  license:
    name: MIT
    url: https://raw.githubusercontent.com/songfei1983/go-api-server/master/LICENSE
  version: "1.0"
paths:
  /keys:
    put:
      consumes:
      - application/json
      description: create an pair of key value
      produces:
      - application/json
      responses:
        "204": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.HTTPError'
      summary: create key value
  /keys/{key}:
    get:
      consumes:
      - application/json
      description: get string by key
      operationId: get-value-by-key
      parameters:
      - description: key
        in: path
        name: key
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.KeyValue'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.HTTPError'
      summary: GetKeyValue a key
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
