name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Start Redis v${{ matrix.redis-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test
      run: go test ./... -bench . -benchmem -benchtime 1s

    - name: Build
      run: go build -v .
