// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Adunit is the predicate function for adunit builders.
type Adunit func(*sql.Selector)
